import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  EXPORT_FILES,
  formatTopRules,
  isPortable,
  renderClaudeMd,
  renderReport,
  renderSkillMd,
  renderWorkstyle,
  rulesLang,
  skillLine,
  writeExports,
  type ExportInput,
} from './exports.ts';
import type { Merged, MergedRule } from './merge.ts';
import { CATEGORIES, type Category, type Confidence } from './runner.ts';

let k = 0;
function rule(category: Category, text: string, confidence: Confidence, frequency: number, chunks: number, over: Partial<MergedRule> = {}): MergedRule {
  k++;
  return {
    key: `key_${k}`,
    category,
    title: `短句${k}`,
    rule: text,
    confidence,
    frequency,
    chunks,
    members: [k],
    evidence: [1, 2, 3, 4].map((i) => ({ id: k * 100 + i, ts: `2026-0${i}-1${i}T09:30`, quote: `引句${k}-${i}` })),
    trigger: null,
    ...over,
  };
}

/** Twelve ranked rules in Chinese, over five categories; debugging and architecture have none. */
function merged(): Merged {
  k = 0;
  const rules = [
    rule('communication', '結論先講，理由放後面。', 'high', 40, 5, { trigger: '看到長篇回報後' }),
    rule('planning', '動手前先給計畫。', 'high', 30, 4),
    rule('communication', '回報用條列編號。', 'medium', 3, 4),
    rule('ai_collaboration', '方向定了就一路做完。', 'medium', 2, 3),
    rule('testing', '有測試才算做完。', 'low', 20, 3),
    rule('implementation', '沿用既有元件。', 'high', 9, 2),
    rule('communication', '不要客套話。', 'high', 8, 2),
    rule('planning', '先開票再動工。', 'high', 7, 2),
    rule('testing', '先重現再修。', 'medium', 6, 1),
    rule('implementation', '後端先行。', 'high', 5, 1),
    rule('ai_collaboration', '卡住就換方法。', 'high', 4, 1, { title: null }),
    rule('communication', '字數上限是硬上限', 'high', 3, 1, { title: null }),
  ];
  return {
    generatedAt: '2026-09-27T01:00:00.000Z',
    findingsSha256: 'f'.repeat(64),
    chunksAnalyzed: 22,
    chunksTotal: 24,
    findings: 71,
    usage: { input: 0, cacheCreation: 0, cacheRead: 0, output: 0, thinking: 0, total: 0 },
    costUsd: 0,
    durationMs: 0,
    dropped: { unknown: 0, duplicate: 0, groups: 0 },
    rules,
  };
}

const input = (): ExportInput => ({ merged: merged(), stats: { prompts: 24045, projects: 61 }, now: new Date(2026, 8, 27, 10) });

test('formatTopRules: the §8 lines, chunks analyzed, ten rules with where they were seen', () => {
  const text = formatTopRules(input());
  const lines = text.split('\n');
  assert.equal(lines[0], 'Rimoo analyzed 24,045 prompts across 61 projects.');
  assert.equal(lines[1], '22 of 24 chunks analyzed.');
  assert.equal(lines[3], 'Your strongest working patterns:');
  assert.equal(lines[5], '1. 結論先講，理由放後面。（出現於 5 段、40 則）');
  assert.equal(lines[14], '10. 後端先行。（出現於 1 段、5 則）');
  assert.equal(text.match(/^\d+\. /gm)!.length, 10);
  assert.doesNotMatch(text, /卡住就換方法/);
  const none = { ...input(), merged: { ...merged(), rules: [] } };
  assert.match(formatTopRules(none), /No working pattern was found\.\n$/);
});

test('report.md: summary on top, every category, confidence, trigger only when known, three dated quotes', () => {
  const md = renderReport(input());
  assert.match(md, /^# Rimoo report\n\nRimoo analyzed 24,045 prompts across 61 projects\.\n22 of 24 chunks analyzed\.\n\nYour strongest working patterns:\n\n1\. 結論先講/);
  for (const title of ['Communication', 'Planning', 'Implementation', 'Testing', 'Debugging', 'Architecture', 'AI collaboration']) {
    assert.match(md, new RegExp(`\\n## ${title}\\n`));
  }
  assert.match(md, /## Debugging\n\n（沒有找到）\n/);
  assert.match(
    md,
    /## Communication\n\n1\. \*\*結論先講，理由放後面。\*\*（出現於 5 段、40 則）\n {3}- Confidence: high\n {3}- Trigger: 看到長篇回報後\n {3}- Quotes:\n {5}- 2026-01-11「引句1-1」\n {5}- 2026-02-12「引句1-2」\n {5}- 2026-03-13「引句1-3」\n\n2\. \*\*回報用條列編號。\*\*（出現於 4 段、3 則）\n {3}- Confidence: medium\n {3}- Quotes:/,
  );
  assert.doesNotMatch(md, /引句1-4/); // three quotes at most
  // Every rule is in, the low one too.
  for (const r of merged().rules) assert.ok(md.includes(r.rule));
});

test('CLAUDE.md: title with the date, rules only if high or medium said 3+ times, no quotes', () => {
  const md = renderClaudeMd(input());
  assert.match(md, /^# How I work with AI \(generated by Rimoo on 2026-09-27\)\n\n以下是從我 24,045 則 Claude Code 歷史訊息抽出來的工作規則。\n\n## Communication\n\n- 結論先講，理由放後面。\n- 回報用條列編號。\n- 不要客套話。\n- 字數上限是硬上限\n\n## Planning\n/);
  assert.doesNotMatch(md, /方向定了就一路做完/); // medium, said twice
  assert.doesNotMatch(md, /有測試才算做完/); // low
  assert.match(md, /- 先重現再修。/); // medium, six times
  assert.doesNotMatch(md, /## Debugging|## Architecture/); // nothing in them
  assert.doesNotMatch(md, /引句|「/);
  assert.deepEqual(
    merged().rules.filter(isPortable).map((r) => r.rule).filter((t) => !md.includes(t)),
    [],
  );
});

test('SKILL.md: frontmatter, ranked rules with a bold lead, same selection as CLAUDE.md, no quotes', () => {
  const md = renderSkillMd(input());
  assert.match(
    md,
    /^---\nname: my-workstyle\ndescription: "從 24,045 則 Claude Code 歷史訊息整理出的個人工作風格，最明顯的是 key_1、key_2、key_3。開始寫程式前載入。"\n---\n\n# My workstyle\n\n以下是從我 24,045 則/,
  );
  assert.match(md, /\n## Rules\n\n1\. \*\*短句1。\*\* 結論先講，理由放後面。\n2\. \*\*短句2。\*\* 動手前先給計畫。\n3\. \*\*短句3。\*\* 回報用條列編號。\n4\. \*\*短句6。\*\* 沿用既有元件。\n/);
  // No title: the rule's own first clause, or all of it.
  assert.match(md, /\n9\. \*\*卡住就換方法。\*\*\n10\. \*\*字數上限是硬上限。\*\*\n$/);
  assert.equal(md.match(/^\d+\. /gm)!.length, merged().rules.filter(isPortable).length);
  assert.doesNotMatch(md, /引句|方向定了|有測試才算/);
});

test('skillLine: title first, else split at the first comma, else the whole rule', () => {
  const r = merged().rules[0]!;
  assert.deepEqual(skillLine(r, 'zh'), { lead: '短句1。', rest: '結論先講，理由放後面。' });
  assert.deepEqual(skillLine({ ...r, title: null }, 'zh'), { lead: '結論先講。', rest: '理由放後面。' });
  assert.deepEqual(skillLine({ ...r, title: null, rule: 'Result first, then the reasons' }, 'en'), {
    lead: 'Result first.',
    rest: 'Then the reasons.',
  });
});

test('workstyle.json: every category as ranked keys, plus the full rule list', () => {
  const w = renderWorkstyle(input());
  assert.deepEqual(Object.keys(w), ['generatedAt', 'prompts', 'projects', ...CATEGORIES, 'rules']);
  assert.equal(w.prompts, 24045);
  assert.equal(w.projects, 61);
  assert.deepEqual(w.communication, ['key_1', 'key_3', 'key_7', 'key_12']);
  assert.deepEqual(w.testing, ['key_5', 'key_9']);
  assert.deepEqual(w.debugging, []);
  assert.equal(w.rules.length, 12);
  assert.deepEqual(w.rules[0], { key: 'key_1', category: 'communication', rule: '結論先講，理由放後面。', frequency: 40, chunks: 5, confidence: 'high' });
  assert.doesNotMatch(JSON.stringify(w), /引句/);
});

test('English rules: English wording around them, quotes in double quotes', () => {
  const m = merged();
  m.rules = m.rules.map((r, i) => ({ ...r, rule: `Rule number ${i + 1}, stated plainly`, title: null }));
  assert.equal(rulesLang(m.rules), 'en');
  const inp = { ...input(), merged: m };
  assert.match(formatTopRules(inp), /\n1\. Rule number 1, stated plainly \(in 5 chunks, 40 messages\)\n/);
  assert.match(renderReport(inp), / {5}- 2026-01-11 "引句1-1"\n/);
  assert.match(renderClaudeMd(inp), /\nThese rules were extracted from 24,045 prompts in my Claude Code history\.\n/);
  assert.match(renderSkillMd(inp), /description: "My working style .* 24,045 Claude Code prompts; strongest: key_1, key_2, key_3\. /);
  assert.match(renderSkillMd(inp), /\n1\. \*\*Rule number 1\.\*\* Stated plainly\.\n/);
});

test('writeExports: the four files, quotes only in report.md', async () => {
  const dir = await mkdtemp(path.join(tmpdir(), 'rimoo-export-'));
  try {
    const files = await writeExports(dir, input());
    assert.deepEqual(files, EXPORT_FILES.map((f) => path.join(dir, f)));
    const [report, claude, skill, workstyle] = await Promise.all(files.map((f) => readFile(f, 'utf8')));
    const quotes = merged().rules.flatMap((r) => r.evidence.slice(0, 3).map((e) => e.quote));
    for (const q of quotes) {
      assert.ok(report!.includes(q), q);
      for (const other of [claude!, skill!, workstyle!]) assert.ok(!other.includes(q), q);
    }
    assert.equal(JSON.parse(workstyle!).prompts, 24045);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});
