import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  EXPORT_FILES,
  formatGate,
  formatTopRules,
  gate,
  isPortable,
  CHECKLIST_MOMENTS,
  renderChecklist,
  renderClaudeMd,
  renderReport,
  renderRulesMd,
  renderShare,
  renderSkillMd,
  renderWorkstyle,
  rulesLang,
  skillLine,
  TOP_SKILL_RULES,
  writeExports,
  type ExportFile,
  type ExportInput,
} from './exports.ts';
import type { Merged, MergedRule } from './merge.ts';
import { CATEGORIES, type Category, type Confidence } from './runner.ts';
import { formatRemoved, type Hit } from './privacy.ts';

let k = 0;
function rule(category: Category, text: string, confidence: Confidence, frequency: number, chunks: number, over: Partial<MergedRule> = {}): MergedRule {
  k++;
  return {
    key: `key_${k}`,
    category,
    title: `短句${k}`,
    rule: text,
    confidence,
    moment: 'always',
    frequency,
    chunks,
    members: [k],
    evidence: [1, 2, 3, 4].map((i) => ({ id: k * 100 + i, ts: `2026-0${i}-1${i}T09:30`, quote: `引句${k}-${i}` })),
    trigger: null,
    ...over,
  };
}

/**
 * Twelve ranked rules in Chinese, over five categories; debugging and architecture have none. Moments: plan 2, 4
 * (not portable), 8; build 6, 9, 10; deliver 1, 3, 5 (low); deploy none; the rest always.
 */
function merged(): Merged {
  k = 0;
  const rules = [
    rule('communication', '結論先講，理由放後面。', 'high', 40, 5, { trigger: '看到長篇回報後', moment: 'deliver' }),
    rule('planning', '動手前先給計畫。', 'high', 30, 4, { moment: 'plan' }),
    rule('communication', '回報用條列編號。', 'medium', 3, 4, { moment: 'deliver' }),
    rule('ai_collaboration', '方向定了就一路做完。', 'medium', 2, 3, { moment: 'plan' }),
    rule('testing', '有測試才算做完。', 'low', 20, 3, { moment: 'deliver' }),
    rule('implementation', '沿用既有元件。', 'high', 9, 2, { moment: 'build' }),
    rule('communication', '不要客套話。', 'high', 8, 2),
    rule('planning', '先開票再動工。', 'high', 7, 2, { moment: 'plan' }),
    rule('testing', '先重現再修。', 'medium', 6, 1, { moment: 'build' }),
    rule('implementation', '後端先行。', 'high', 5, 1, { moment: 'build' }),
    rule('ai_collaboration', '卡住就換方法。', 'high', 4, 1, { title: null }),
    rule('communication', '字數上限是硬上限', 'high', 3, 1, { title: null }),
  ];
  return {
    generatedAt: '2026-09-27T01:00:00.000Z',
    findingsSha256: 'f'.repeat(64),
    chunksAnalyzed: 22,
    chunksTotal: 24,
    findings: 71,
    usage: { input: 0, cacheCreation: 0, cacheRead: 0, output: 0, thinking: 0, total: 0 },
    costUsd: 0,
    durationMs: 0,
    dropped: { unknown: 0, duplicate: 0, groups: 0 },
    rules,
  };
}

const input = (): ExportInput => ({ merged: merged(), stats: { prompts: 24045, projects: 61 }, now: new Date(2026, 8, 27, 10) });

test('formatTopRules: the §8 lines, chunks analyzed, ten rules with where they were seen', () => {
  const text = formatTopRules(input());
  const lines = text.split('\n');
  assert.equal(lines[0], 'Rimoo analyzed 24,045 prompts across 61 projects.');
  assert.equal(lines[1], '22 of 24 chunks analyzed.');
  assert.equal(lines[3], 'Your strongest working patterns:');
  assert.equal(lines[5], '1. 結論先講，理由放後面。（出現於 5 段、40 則）');
  assert.equal(lines[14], '10. 後端先行。（出現於 1 段、5 則）');
  assert.equal(text.match(/^\d+\. /gm)!.length, 10);
  assert.doesNotMatch(text, /卡住就換方法/);
  const none = { ...input(), merged: { ...merged(), rules: [] } };
  assert.match(formatTopRules(none), /No working pattern was found\.\n$/);
});

test('report.md: summary on top, every category, confidence, trigger only when known, three dated quotes', () => {
  const md = renderReport(input());
  assert.match(md, /^# Rimoo report\n\nRimoo analyzed 24,045 prompts across 61 projects\.\n22 of 24 chunks analyzed\.\n\nYour strongest working patterns:\n\n1\. 結論先講/);
  for (const title of ['Communication', 'Planning', 'Implementation', 'Testing', 'Debugging', 'Architecture', 'AI collaboration']) {
    assert.match(md, new RegExp(`\\n## ${title}\\n`));
  }
  assert.match(md, /## Debugging\n\n（沒有找到）\n/);
  assert.match(
    md,
    /## Communication\n\n1\. \*\*結論先講，理由放後面。\*\*（出現於 5 段、40 則）\n {3}- Confidence: high\n {3}- Trigger: 看到長篇回報後\n {3}- Quotes:\n {5}- 2026-01-11「引句1-1」\n {5}- 2026-02-12「引句1-2」\n {5}- 2026-03-13「引句1-3」\n\n2\. \*\*回報用條列編號。\*\*（出現於 4 段、3 則）\n {3}- Confidence: medium\n {3}- Quotes:/,
  );
  assert.doesNotMatch(md, /引句1-4/); // three quotes at most
  // Every rule is in, the low one too.
  for (const r of merged().rules) assert.ok(md.includes(r.rule));
});

test('CLAUDE.md: title with the date, rules only if high or medium said 3+ times, no quotes', () => {
  const md = renderClaudeMd(input());
  assert.match(md, /^# How I work with AI \(generated by Rimoo on 2026-09-27\)\n\n以下是從我 24,045 則 Claude Code 歷史訊息抽出來的工作規則。\n\n## Communication\n\n- 結論先講，理由放後面。\n- 回報用條列編號。\n- 不要客套話。\n- 字數上限是硬上限\n\n## Planning\n/);
  assert.doesNotMatch(md, /方向定了就一路做完/); // medium, said twice
  assert.doesNotMatch(md, /有測試才算做完/); // low
  assert.match(md, /- 先重現再修。/); // medium, six times
  assert.doesNotMatch(md, /## Debugging|## Architecture/); // nothing in them
  assert.doesNotMatch(md, /引句|「/);
  assert.deepEqual(
    merged().rules.filter(isPortable).map((r) => r.rule).filter((t) => !md.includes(t)),
    [],
  );
});

test('SKILL.md: frontmatter, the three usage lines, ranked rules with a bold lead, same selection as CLAUDE.md, no quotes', () => {
  const md = renderSkillMd(input());
  assert.match(
    md,
    /^---\nname: my-workstyle\ndescription: "從 24,045 則 Claude Code 歷史訊息整理出的個人工作風格，最明顯的是 key_1、key_2、key_3。開始寫程式前載入。"\nargument-hint: "\[plan\|build\|deliver\|deploy\]"\n---\n\n# My workstyle\n\n這是什麼：Rimoo 從 24,045 則 Claude Code 歷史訊息抽出的 10 條規則。\n怎麼用：在 Claude Code 對話開頭輸入 \/my-workstyle；要規劃、動手、交付或上線前，輸入 \/my-workstyle plan、build、deliver 或 deploy，逐項看過那一步的清單。想在某個專案一直套用，把 CLAUDE\.md 複製到那個專案的根目錄。\n更多：全部規則在同一個資料夾的 rules\.md。\n\n## Rules\n/,
  );
  assert.match(md, /\n## Rules\n\n1\. \*\*短句1。\*\* 結論先講，理由放後面。\n2\. \*\*短句2。\*\* 動手前先給計畫。\n3\. \*\*短句3。\*\* 回報用條列編號。\n4\. \*\*短句6。\*\* 沿用既有元件。\n/);
  // No title: the rule's own first clause, or all of it.
  assert.match(md, /\n9\. \*\*卡住就換方法。\*\*\n10\. \*\*字數上限是硬上限。\*\*\n\n## When invoked with an argument\n\nIf \$ARGUMENTS is one of plan, build, deliver or deploy, read checklists\/\$ARGUMENTS\.md in this folder and go through every line before acting\. Any other text is the task to do under these rules\.\n\n全部規則見 rules\.md（10 條）\n$/);
  assert.equal(md.match(/^\d+\. /gm)!.length, merged().rules.filter(isPortable).length);
  assert.doesNotMatch(md, /引句|方向定了|有測試才算/);
  assert.match(renderSkillMd({ ...input(), skillName: 'team-style' }), /^---\nname: team-style\n[\s\S]*輸入 \/team-style；[\s\S]*輸入 \/team-style plan、/);
});

/** The fixture plus eight more portable rules, so there are more than TOP_SKILL_RULES. */
function many(): ExportInput {
  const m = merged();
  for (let i = 1; i <= 8; i++) m.rules.push(rule('planning', `多出來的第 ${i} 條。`, 'high', 2, 1));
  return { ...input(), merged: m };
}

test('SKILL.md: exactly the top 12 portable rules in rank order, then the pointer to rules.md', () => {
  const inp = many();
  const portable = inp.merged.rules.filter(isPortable);
  assert.equal(portable.length, 18);
  const md = renderSkillMd(inp);
  const leads = [...md.matchAll(/^\d+\. \*\*(.+?)\*\*/gm)].map((x) => x[1]);
  assert.equal(leads.length, TOP_SKILL_RULES);
  assert.deepEqual(leads, portable.slice(0, TOP_SKILL_RULES).map((r) => skillLine(r, 'zh').lead));
  assert.match(md, /\n12\. \*\*短句14。\*\* 多出來的第 2 條。\n\n## When invoked with an argument\n\n[^\n]+\n\n全部規則見 rules\.md（18 條）\n$/);
  assert.doesNotMatch(md, /多出來的第 3 條/);
  assert.match(md, /抽出的 18 條規則/);
});

test('rules.md: every portable rule in rank order, same form as SKILL.md', () => {
  const inp = many();
  const portable = inp.merged.rules.filter(isPortable);
  const md = renderRulesMd(inp);
  assert.match(md, /^# Rules\n\n以下是從我 24,045 則 Claude Code 歷史訊息抽出來的工作規則。\n\n1\. \*\*短句1。\*\* 結論先講，理由放後面。\n/);
  assert.equal(md.match(/^\d+\. /gm)!.length, portable.length);
  assert.match(md, /\n18\. \*\*短句20。\*\* 多出來的第 8 條。\n$/);
  assert.doesNotMatch(md, /引句|方向定了|有測試才算/);
});

test('English rules: SKILL.md usage lines and the rules.md pointer in English', () => {
  const m = many().merged;
  m.rules = m.rules.map((r, i) => ({ ...r, rule: `Rule number ${i + 1}, stated plainly`, title: null }));
  const md = renderSkillMd({ ...input(), merged: m });
  assert.match(
    md,
    /\n# My workstyle\n\nWhat this is: 18 rules extracted from 24,045 Claude Code prompts by Rimoo\.\nHow to use: type \/my-workstyle at the start of a Claude Code session, or \/my-workstyle plan, build, deliver or deploy right before that step to go through its checklist\. To have them always on in a project, copy CLAUDE\.md into its root\.\nMore: the full list is in rules\.md next to this file\.\n\n## Rules\n/,
  );
  assert.match(md, /\n\n## When invoked with an argument\n\n[^\n]+\n\nFull list: rules\.md \(18 rules\)\n$/);
  assert.match(renderRulesMd({ ...input(), merged: m }), /^# Rules\n\nThese rules were extracted from 24,045 prompts in my Claude Code history\.\n\n1\. \*\*Rule number 1\.\*\* Stated plainly\.\n/);
});

test('checklists: each has only its own portable rules, in rank order, as tick boxes; an empty one says so', () => {
  const inp = input();
  assert.equal(
    renderChecklist(inp, 'plan'),
    '# 規劃前（plan）\n\n逐項看過再動手；沒過的先處理。\n\n- [ ] **短句2。** 動手前先給計畫。\n- [ ] **短句8。** 先開票再動工。\n',
  );
  assert.equal(
    renderChecklist(inp, 'build'),
    '# 動手前（build）\n\n逐項看過再動手；沒過的先處理。\n\n- [ ] **短句6。** 沿用既有元件。\n- [ ] **短句9。** 先重現再修。\n- [ ] **短句10。** 後端先行。\n',
  );
  // 有測試才算做完 is deliver too, but low: not in.
  assert.equal(
    renderChecklist(inp, 'deliver'),
    '# 交付前（deliver）\n\n逐項看過再動手；沒過的先處理。\n\n- [ ] **短句1。** 結論先講，理由放後面。\n- [ ] **短句3。** 回報用條列編號。\n',
  );
  assert.equal(renderChecklist(inp, 'deploy'), '# 上線前（deploy）\n\n這個時機還沒有規則。\n');
  // Every portable rule that is not always is in exactly one checklist.
  const all = CHECKLIST_MOMENTS.map((m) => renderChecklist(inp, m)).join('');
  for (const r of merged().rules.filter(isPortable)) {
    assert.equal(all.includes(r.rule), r.moment !== 'always', r.rule);
  }

  const m = merged();
  m.rules = m.rules.map((r, i) => ({ ...r, rule: `Rule number ${i + 1}, stated plainly`, title: null }));
  const en = { ...input(), merged: m };
  assert.equal(
    renderChecklist(en, 'plan'),
    '# Before planning (plan)\n\nGo through every line before you start; fix what fails first.\n\n- [ ] **Rule number 2.** Stated plainly.\n- [ ] **Rule number 8.** Stated plainly.\n',
  );
  assert.match(renderChecklist(en, 'build'), /^# Before building \(build\)\n/);
  assert.match(renderChecklist(en, 'deliver'), /^# Before delivering \(deliver\)\n/);
  assert.equal(renderChecklist(en, 'deploy'), '# Before deploying (deploy)\n\nNo rule found for this moment yet.\n');
});

test('writeExports: the four checklists in checklists/, written as rendered', async () => {
  const dir = await mkdtemp(path.join(tmpdir(), 'rimoo-export-'));
  try {
    const written: string[] = [];
    await writeExports(dir, input(), { onWritten: (f) => written.push(f) });
    for (const m of CHECKLIST_MOMENTS) {
      assert.equal(await readFile(path.join(dir, 'checklists', `${m}.md`), 'utf8'), renderChecklist(input(), m));
      assert.ok(written.includes(`checklists/${m}.md`), m);
    }
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('skillLine: title first, else split at the first comma, else the whole rule', () => {
  const r = merged().rules[0]!;
  assert.deepEqual(skillLine(r, 'zh'), { lead: '短句1。', rest: '結論先講，理由放後面。' });
  assert.deepEqual(skillLine({ ...r, title: null }, 'zh'), { lead: '結論先講。', rest: '理由放後面。' });
  assert.deepEqual(skillLine({ ...r, title: null, rule: 'Result first, then the reasons' }, 'en'), {
    lead: 'Result first.',
    rest: 'Then the reasons.',
  });
});

test('workstyle.json: every category as ranked keys, plus the full rule list', () => {
  const w = renderWorkstyle(input());
  assert.deepEqual(Object.keys(w), ['generatedAt', 'prompts', 'projects', ...CATEGORIES, 'rules']);
  assert.equal(w.prompts, 24045);
  assert.equal(w.projects, 61);
  assert.deepEqual(w.communication, ['key_1', 'key_3', 'key_7', 'key_12']);
  assert.deepEqual(w.testing, ['key_5', 'key_9']);
  assert.deepEqual(w.debugging, []);
  assert.equal(w.rules.length, 12);
  assert.deepEqual(w.rules[0], { key: 'key_1', category: 'communication', rule: '結論先講，理由放後面。', frequency: 40, chunks: 5, confidence: 'high' });
  assert.doesNotMatch(JSON.stringify(w), /引句/);
});

test('English rules: English wording around them, quotes in double quotes', () => {
  const m = merged();
  m.rules = m.rules.map((r, i) => ({ ...r, rule: `Rule number ${i + 1}, stated plainly`, title: null }));
  assert.equal(rulesLang(m.rules), 'en');
  const inp = { ...input(), merged: m };
  assert.match(formatTopRules(inp), /\n1\. Rule number 1, stated plainly \(in 5 chunks, 40 messages\)\n/);
  assert.match(renderReport(inp), / {5}- 2026-01-11 "引句1-1"\n/);
  assert.match(renderClaudeMd(inp), /\nThese rules were extracted from 24,045 prompts in my Claude Code history\.\n/);
  assert.match(renderSkillMd(inp), /description: "My working style .* 24,045 Claude Code prompts; strongest: key_1, key_2, key_3\. /);
  assert.match(renderSkillMd(inp), /\n1\. \*\*Rule number 1\.\*\* Stated plainly\.\n/);
});

test('writeExports: every file, quotes only in report.md', async () => {
  const dir = await mkdtemp(path.join(tmpdir(), 'rimoo-export-'));
  try {
    const files = await writeExports(dir, input());
    assert.deepEqual(files, EXPORT_FILES.map((f) => path.join(dir, f)));
    assert.equal(EXPORT_FILES.indexOf('rules.md'), EXPORT_FILES.indexOf('SKILL.md') + 1);
    const text = Object.fromEntries(await Promise.all(EXPORT_FILES.map(async (f) => [f, await readFile(path.join(dir, f), 'utf8')] as const)));
    const [report, claude, skill, rules, workstyle] = ['report.md', 'CLAUDE.md', 'SKILL.md', 'rules.md', 'workstyle.json'].map((f) => text[f]);
    const quotes = merged().rules.flatMap((r) => r.evidence.slice(0, 3).map((e) => e.quote));
    for (const q of quotes) {
      assert.ok(report!.includes(q), q);
      for (const [f, other] of Object.entries(text)) if (f !== 'report.md') assert.ok(!other.includes(q), `${f}: ${q}`);
    }
    assert.equal(rules, renderRulesMd(input()));
    assert.equal(JSON.parse(workstyle!).prompts, 24045);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('share.txt: prompts, projects, the top five portable rules by title, the footer; English wording for English rules', () => {
  assert.equal(
    renderShare(input()),
    [
      '我跟 AI 寫程式的習慣',
      '',
      '分析了 24,045 則訊息',
      '61 個專案',
      '',
      '最常出現的習慣：',
      '• 短句1',
      '• 短句2',
      '• 短句3',
      '• 短句6',
      '• 短句7',
      '',
      '用 Rimoo 整理：npx rimoo analyze',
      '',
    ].join('\n'),
  );
  const m = merged();
  m.rules = m.rules.map((r, i) => ({ ...r, rule: `Rule number ${i + 1}.`, title: i === 0 ? 'Result first' : null }));
  const en = renderShare({ merged: m, stats: { prompts: 1, projects: 1 } });
  assert.equal(
    en,
    'My AI coding workstyle\n\n1 prompt analyzed\n1 project\n\nTop patterns:\n• Result first\n• Rule number 2\n• Rule number 3\n• Rule number 6\n• Rule number 7\n\nFound with Rimoo — npx rimoo analyze\n',
  );
  const none = renderShare({ ...input(), merged: { ...merged(), rules: [] } });
  assert.doesNotMatch(none, /最常出現|•/);
});

/** A rule carrying a fake key, a path, an email, a URL and a phone number, ranked first. */
function leaky(): ExportInput {
  const m = merged();
  const text = '金鑰 sk-abcdefghijklmnop1234 放 /data/repos/secret-app，寄 me@corp.example，看 https://corp.example/wiki，打 0912-345-678';
  m.rules[0] = { ...m.rules[0]!, rule: text, title: '別放 /home/me/.env' };
  return { ...input(), merged: m };
}

test('privacy gate: each file removed as its policy says, written anyway, lines reported where they are', async () => {
  const dir = await mkdtemp(path.join(tmpdir(), 'rimoo-gate-'));
  try {
    const removed: { file: ExportFile; hits: Hit[] }[] = [];
    const files = await writeExports(dir, leaky(), { onRemoved: (file, hits) => removed.push({ file, hits }) });
    const text = Object.fromEntries(await Promise.all(files.map(async (f) => [path.relative(dir, f).split(path.sep).join('/'), await readFile(f, 'utf8')] as const)));
    const kindsOf = (file: string): string[] => removed.find((r) => r.file === file)?.hits.map((h) => h.kind) ?? [];

    // report.md keeps the user's own words: only the key goes.
    assert.ok(!text['report.md']!.includes('sk-abcdefghijklmnop1234'));
    for (const kept of ['/data/repos/secret-app', 'me@corp.example', 'https://corp.example/wiki', '0912-345-678']) assert.ok(text['report.md']!.includes(kept), kept);
    assert.deepEqual([...new Set(kindsOf('report.md'))], ['secret']);

    // The shared files lose all five.
    for (const f of ['CLAUDE.md', 'SKILL.md', 'rules.md', 'checklists/deliver.md', 'workstyle.json', 'share.txt']) {
      for (const leak of ['sk-abcdefghijklmnop1234', '/data/repos', '/home/me', 'me@corp.example', 'corp.example/wiki', '0912-345-678']) {
        assert.ok(!text[f]!.includes(leak), `${f}: ${leak}`);
      }
      assert.ok(text[f]!.includes('[removed]'), f);
    }
    assert.deepEqual([...new Set(kindsOf('CLAUDE.md'))].sort(), ['email', 'path', 'phone', 'secret', 'url']);
    assert.deepEqual(kindsOf('share.txt'), ['path']); // share.txt shows the title only
    assert.deepEqual([...new Set(kindsOf('rules.md'))].sort(), ['email', 'path', 'phone', 'secret', 'url']);
    assert.equal(JSON.parse(text['workstyle.json']!).rules[0].rule, '金鑰 [removed] 放 [removed]，寄 [removed]，看 [removed]，打 [removed]');

    // The reported line is the line the removal is on.
    for (const { file, hits } of removed) {
      const lines = text[file]!.split('\n');
      for (const h of hits) assert.ok(lines[h.line - 1]!.includes('[removed]'), `${file} line ${h.line}`);
    }
    const claudeLine = text['CLAUDE.md']!.split('\n').findIndex((l) => l.startsWith('- 金鑰')) + 1;
    assert.equal(
      formatGate(removed.filter((r) => r.file === 'CLAUDE.md')),
      `  Removed from CLAUDE.md: 1 file path (line ${claudeLine}), 1 email address (line ${claudeLine}), 1 URL (line ${claudeLine}), 1 phone number (line ${claudeLine}), 1 key or token (line ${claudeLine}). Pass --allow-paths to keep paths and project names.\n`,
    );
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('privacy gate: --allow-paths keeps paths and only paths; clean rules call nothing', async () => {
  const { text, hits } = gate('SKILL.md', renderSkillMd(leaky()), true);
  assert.ok(text.includes('/data/repos/secret-app'));
  assert.ok(text.includes('/home/me/.env'));
  assert.ok(!text.includes('me@corp.example'));
  assert.ok(!hits.some((h) => h.kind === 'path'));
  assert.doesNotMatch(formatRemoved('SKILL.md', hits), /allow-paths/);
  let called = 0;
  const dir = await mkdtemp(path.join(tmpdir(), 'rimoo-gate-'));
  try {
    await writeExports(dir, input(), { onRemoved: () => called++ });
    assert.equal(called, 0);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('gate: project names are removed from CLAUDE.md but kept in report.md', () => {
  const names = ['toy-app'];
  assert.equal(gate('CLAUDE.md', '- reuse the toy-app layout\n', false, names).text, '- reuse the [removed] layout\n');
  assert.equal(gate('report.md', '- reuse the toy-app layout\n', false, names).text, '- reuse the toy-app layout\n');
  assert.equal(gate('CLAUDE.md', '- reuse the toy-app layout\n', true, names).hits.length, 0);
});
